### PR TITLE
Restrict groups in dropdown

### PR DESCRIPTION
**Pull request by Akuket**
Now can restrict groups visibility in the dropdown.

After creating a new ItilCategory Group and define the rank of all groups (n0, n+1, n+2,...) these ones are now used to apply a filter in the dropdown of the ticket. Only n and n+1 levels can be selected.
If no rule, no filter is applied.

### CODE REVIEW

**Comment by cedric-anne** [comment]
Hi,

Most of your changes are just about coding standards, and this is a problem for readability of your PR.
Please revert your changes on this and keep only what matters.

Regards

**Comment by Akuket** [comment]
What coding standards do you use ?

**Comment by trasher** [comment]
https://glpi-developer-documentation.readthedocs.io/en/latest/codingstandards.html

**Comment by Akuket** [comment]
Hi,

Everything is good for you?

Regards

**Comment by Akuket** [comment]
Hello,

Someone to proceed to the merge or tell me what I need to change if needed?
Thanks.

Regards

**Comment by trasher** [comment]
There are still many unneeded change, see the diff.

**Comment by Akuket** [comment]
Ok, now it's ok

**Comment by GuiGuiSoft** [comment]
Hello,

Modifications seems more readable now, will this pull request be merged soon ?

Regards.

**Comment by Akuket** [comment]
Hello,

Someone to proceed to the merge or tell me what I need to change if needed?
Thanks.

Regards

**Comment by orthagh** [comment]
I'll do review today.

**Comment by Akuket** [comment]
Thanks :)

**Comment by orthagh** [comment]
I just cloned your work on my computer, and trying to understand the difference with current code, and somehow fail to.

Could you provide some example (screenshots ?) with before / after applying your changes ?

Regards.

**Comment by Akuket** [comment]
Yes, of course, I'll post it probably on Monday

**Comment by Akuket** [comment]
Hello,
Here's an example of what it can do with my changes.

Configuration of my category group
image

We attribute the ticket to the first group
image

And when we want to escalade to another group, this is only what we can see
image

Regards

**Comment by orthagh** [comment]
Ok i understant the change.

You enforce the filter by displaying:
- only first level when no group yet assigned
- only the next level of the current group assigned.

So your PR is ok, but it changes the default behavior of the plugin which is currently used by another users.

To be merged, i need you add a parameter in the category form to choose the behavior when selecting a category in a ticket:
- display all available groups (default)
- diplay only the groups on the next level.

We have space here to insert the dropdown:
image

So set your changes as optional, and it will be OK for merge on my side.

**Comment by Akuket** [comment]
Changes are done. Sorry for the wait.

**Comment by Akuket** [comment]
Hello,

Someone to proceed to the merge or tell me what I need to change if needed?
Thanks.

Regards

**Comment by orthagh** [comment]
Ok for me, merged

**Comment by orthagh** [comment]
And released: https://github.com/pluginsGLPI/itilcategorygroups/releases/tag/2.3.0

Sorry for the long delay at managing this pr, a lot of work on our side on the glpi core project

**Pull request merged**
